@Nager.PublicSuffix.WebApi_HostAddress = http://localhost:5096

GET {{Nager.PublicSuffix.WebApi_HostAddress}}/DomainInfo/test.de/
Accept: application/json
###

GET {{Nager.PublicSuffix.WebApi_HostAddress}}/DomainInfo/mail.test.de/
Accept: application/json

###

GET {{Nager.PublicSuffix.WebApi_HostAddress}}/DomainInfo/s3-1.amazonaws.com/
Accept: application/json

###
